config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  resources :locations do
    resources :bookings, only: [:new, :create]
    resources :photos, only: [:new, :create, :destroy]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :location
  belongs_to :user
  has_one :review
  validates :entry_date, presence: true
  validates :exit_date, presence: true
  validate :not_blank_date
  after_validation :set_price

  def set_price
    if !entry_date.nil? && !exit_date.nil?
      self.booking_price = self.location.price * (self.exit_date - self.entry_date).to_i
    end
  end

  def not_blank_date
    if !entry_date.nil? && !exit_date.nil?
      errors.add(:entry_date, "can't be in the past") if entry_date < Date.today
      errors.add(:entry_date, "can't be after the exit date") if entry_date > exit_date
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reviews
  validates :user, presence: true
  validates :name, :address, :price, :user, :description, :cover, presence: true

  mount_uploader :cover, PhotoUploader

  include PgSearch
  pg_search_scope :global_search,
    against: [:address, :name, :description],
    associated_against: {
    user: [:first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def avg_rating
    total = self.reviews.count
    total_sum = 0.0
    if self.reviews.exists?
      self.reviews.each do |review|
        total_sum += review.rating
      end
      raw_rating = total_sum / total
      (raw_rating * 2).round.to_f / 2
    else
      0
    end
  end

  def avg_rating_dec
    total = self.reviews.count
    total_sum = 0.0
    if self.reviews.exists?
      self.reviews.each do |review|
        total_sum += review.rating
      end
      (total_sum.to_f / total).round(1)
    else
      return 0.0
    end
  end

  def reviews_count
    if self.reviews.count.nil?
      return 0
    else
      return self.reviews.count
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :location

  mount_uploader :picture, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :location
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :photo, presence: true
  has_many  :bookings
  has_many  :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :dashboard, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :photo_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :photo_cache])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @location = Location.find(params[:location_id])
    @booking.location = @location
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render template: "locations/show"

    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:entry_date, :exit_date)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      sql_query = " \
        locations.name ILIKE :query \
        OR locations.address ILIKE :query \
        OR locations.description ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
      "
      @locations = Location.joins(:user).where(sql_query, query: "%#{params[:query]}%").where.not(latitude: nil, longitude: nil)
      set_markers
    else
      @locations = Location.all
      set_markers
    end
  end

  def show
    @location = Location.find(params[:id])
    @booking = Booking.new
    @average_rating = @location.avg_rating
    @no_of_reviews = @location.reviews_count
    @avg_rating_dec = @location.avg_rating_dec
  end

  def new
    @location = Location.new
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    authorize @location
    @location.user = current_user

    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize @location
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)
    if @location.save
      redirect_to location_path(@location)
    else
      render :edit
    end
  end

  private

  def set_markers
    @markers = @locations.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { location: location }),
      }
    end
  end

  def set_locations
    @locations = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :address, :price, :description, :cover)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @locations = policy_scope(Location)
    @bookings_made = policy_scope(Booking)
    @bookings_rec = BookingPolicy::Scope.new(current_user, Booking).bookings_received
    @review = Review.new
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @location = Location.find(params[:location_id])
    @photo = Photo.new
    @photo.location = @location
    authorize @photo
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.location = Location.find(params[:location_id])
    authorize @photo
    if @photo.save
      redirect_to location_path(@photo.location)
    else
      render :new
    end


  end

  # def delete
  #   @photo = Photo.find(params[:id])
  #   @photo.destroy
  # end

  private

  def set_photos
    @photos = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:picture)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    authorize @review
    if @booking.review
      redirect_to locations_path
    else
      @review.booking = @booking
      @review.location = @booking.location
      if @review.save
        redirect_to dashboard_path
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container">
  <h2>Booking Confirmed</h2>
  <div class="card-trip">
    <%= cl_image_tag @booking.location.cover %>
    <div class="card-trip-infos">
      <div>
        <h2 class="py-2"><%= link_to @booking.location.name, location_path(@booking.location), { class: "nounderline" } %></h2>
        <p class="py-1"><%= @booking.location.address %></p>
        <p class="py-1">Booking for:</p>
        <p class="py-1">Start Date: <%= @booking.entry_date %></p>
        <p class="py-1">End Date: <%= @booking.exit_date %></p>
        <p class="py-1">Renter: <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>
        <p class="py-1">Owner: <%= @booking.location.user.first_name %> <%= @booking.location.user.last_name %></p>
      </div>
      <h2 class="card-trip-pricing"><i class="fas fa-rupee-sign"></i> <%= @booking.booking_price %></h2>
      <%= cl_image_tag @booking.location.user.photo, height: 80, width: 80, :crop=>"thumb", :gravity=>"faces", class: "card-trip-user avatar-bordered" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Green Room Locations</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600,700&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/locations/_infowindow.html.erb
<%= link_to location_path(location), { class: "nounderline" } do %>
<div class="infowindow-pop">
  <div class="">
    <div>
      <h5><%= location.name %></h5>
    </div>
    <div>
      <img class="img-map" src="<%= location.cover %>" alt="">
    </div>
    <div>
      <h6><%= location.address %></h6>
    </div>
    <div>
      <p><i class="fas fa-rupee-sign"></i> <%= location.price %></p>
    </div>
  </div>
</div>
<% end %>

app/views/locations/edit.html.erb
<div style="background-image: url('https://images.pexels.com/photos/509922/pexels-photo-509922.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
  <div class="container">
    <div class="mb-3">
        <div class="new-form">
          <h2>Add new location</h2>
          <%= simple_form_for(@location) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :price %>
              <%= f.input :description %>
              <%= f.input :cover %>
              <%= f.input :cover_cache, as: :hidden %>
              <%= f.button :submit, class: "text-white btn btn-primary" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div>
  <div class="card-banner" style="background-image: url('https://images.pexels.com/photos/1471203/pexels-photo-1471203.jpeg?cs=srgb&dl=city-lights-dark-dark-green-plants-1471203.jpg&fm=jpg');">
    <div class="card-ban-title"><h1>Add your locations</h1></div>
    <a href="/locations/new" class="index-btn btn btn-primary btn-lg text-right">New</a>
  </div>
</div>



<div class="main-container">
  <div class="cards-index">
      <% @locations.each do |location| %>
      <%= link_to location_path(location), { class: "nounderline" } do %>
        <div class="card">
          <div class="card-wraper" style=" background-color: white;">
            <div class="card-img" style="background-image: url('<%= location.cover %>');">
              <h1 class="card-title"><h5><%= location.name %></h5></h1>
              <h6><%= location.address %></h6>
            </div>
            <div class="card-action">
              <div>
                <i class="fas fa-rupee-sign"></i> <%= location.price %>
              </div>
            </div>
          </div>
        </div>
         <% end %>
      <% end %>
  </div>
  <div
    id="map"
    style="width: 60%;
    height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/locations/new.html.erb
<div class="new-location-container">
  <div class="container col-5">
    <div class="back-color">
        <div class="new-form">
          <h3 class="text-center pb-4">Add new location</h3>
          <%= simple_form_for(@location) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :price %>
              <%= f.input :description %>
              <%= f.input :cover %>
              <%= f.input :cover_cache, as: :hidden %>
              <%= f.button :submit, class: "text-white btn btn-primary new-button" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>
</div>

app/views/locations/show.html.erb
<div class="d-flex">
  <div class="big-name">
    <h1><%= @location.name %></h1>
    <p><strong>Rating: </strong> <%= @avg_rating_dec %>
        <% @average_rating.floor.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% if (@average_rating / 0.5).to_i.odd? %>
          <i class="fas fa-star-half-alt"></i>
          <% (5 - @average_rating).floor.times do %>
            <i class="far fa-star"></i>
          <% end %>
        <% else %>
          <% (5 - @average_rating).floor.times do %>
            <i class="far fa-star"></i>
          <% end %>
        <% end %>
      (<%= @no_of_reviews %>)</p>
  </div>
  <div class="show-img text-right pr-5" style="background-image: url('<%= @location.cover %>');">
    <% if @location.user == current_user %>
    <%= link_to "upload photos", new_location_photo_path(@location.id), class: "show-btn btn btn-primary text-right"  %>
    <% end %>
  </div>
</div>

<div class="d-flex px-3 py-4" style="background-color: white;">
  <div class="col-4 justify-content-end">
    <h5>Description</h5>
    <h5 class="body-text"><%= @location.description %></h5>
  </div>
  <div class="col-4 text-right">
    <div class="">
    <div>
    <h5>Rented by</h5><%= cl_image_tag @location.user.photo, height: 45, width: 45, :crop=>"thumb", :gravity=>"faces", :radius=>"max" %>
      <h5 class="body-text"><%= @location.user.first_name %> <%= @location.user.last_name %></h5>
    </div>
    <div class="text-right">
      <h6>Daily rate</h6>
      <i class="fas fa-rupee-sign"></i> <%= @location.price %>
      </div>
      </div>
  </div>
  <div class="col-4 text-right pr-4">
    <h3>New Booking</h3>
    <%= simple_form_for [@location, @booking] do |f| %>
      <div class="form-inputs">
        <%= f.input :entry_date, as: :date, html5: true %>
        <%= f.input :exit_date, as: :date, html5: true %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: "create-btn btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<div class="d-flex">
  <div
    id="map"
    style="width: 100%;
    height: 100vh;"
    data-markers="<%= [{lat: @location.latitude, lng: @location.longitude}].to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="container">
    <div class="row">
      <% @location.photos.each do |photo| %>
      <div class="col-4 mt-2 ">
        <div class="card-img" style="background-image: url('<%= photo.picture %>');">
        </div>
      </div>
      <% end %>
    </div>
    <div class="reviews pt-4">
      <h3>Reviews (<%= @no_of_reviews %>)</h3>
      <% @location.reviews.each do |review| %>
      <div class="border p-3 my-3 rounded review-card">
        <p><strong>Rating: </strong>
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
        <p><%= review.content %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="location-tab" data-toggle="tab" href="#location" role="tab" aria-controls="location" aria-selected="true">My Locations</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="bookings-made-tab" data-toggle="tab" href="#bookings-made" role="tab" aria-controls="bookings-made" aria-selected="false">Booking Made</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="bookings-received-tab" data-toggle="tab" href="#bookings-received" role="tab" aria-controls="bookings-received" aria-selected="false">Bookings Received</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="location" role="tabpanel" aria-labelledby="location-tab">
      <h3 class="mt-4">My Locations</h3>
      <% @locations.each do |location| %>
      <%= link_to location_path(location), { class: "nounderline" } do %>
      <div class="card-product my-2">
        <%= cl_image_tag location.cover, class: "img" %>
        <div class="card-product-infos nounderline">
          <h2><%= location.name %></h2>
          <p><%= location.address %></p>
          <p>Daily price: <i class="fas fa-rupee-sign"></i> <%= location.price %></p>
        </div>
      </div>
      <% end %>
      <% end %>
      <% if policy(Location).create? %>
      <%= link_to "New Location", new_location_path %>
      <% end %>
    </div>

    <div class="tab-pane fade" id="bookings-made" role="tabpanel" aria-labelledby="bookings-made-tab">
      <h3 class="mt-4">Bookings Made</h3>
      <% @bookings_made.each do |booking| %>
      <div class="card-product my-2 d-flex justify-content-between">
        <%= link_to booking_path(booking), { class: "nounderline" } do %>
        <div class="d-flex">
          <%= cl_image_tag booking.location.cover, class: "img" %>
          <div class="card-product-infos nounderline">
            <h2><%= booking.location.name %></h2>
            <p><%= booking.location.address %></p>
            <p>Booked for: <%= booking.entry_date %> - <%= booking.exit_date %></p>
            <p>Total price: <i class="fas fa-rupee-sign"></i> <%= booking.booking_price %></p>
          </div>
        </div>
        <% end %>
        <div class="pr-3 dashboard-review">
          <% if !booking.review %>
            <button type="button" class="btn btn-primary modal-review-button" data-booking="<%= booking.id %>" data-toggle="modal" data-target="#reviewModal">
              Leave a Review
            </button>
            <% else %>
            <div>
              <h3>Your review:</h3>
              <p><% booking.review.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% (5 - booking.review.rating).times do %>
                  <i class="far fa-star"></i>
                <% end %>
              </p>
            </div>
            <div>
              <p><%= booking.review.content %></p>
            </div>
          <% end %>
        </div>

      </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="bookings-received" role="tabpanel" aria-labelledby="bookings-received-tab">
      <h3 class="mt-4">Bookings Received</h3>
      <% @bookings_rec.each do |booking| %>
      <%= link_to booking_path(booking), { class: "nounderline" } do %>
      <div class="card-product my-2">
        <%= cl_image_tag booking.location.cover, class: "img" %>
        <div class="card-product-infos nounderline">
          <h2><%= booking.location.name %></h2>
          <p><%= booking.location.address %></p>
          <p>Booked for: <%= booking.entry_date %> - <%= booking.exit_date %></p>
          <p>Total price: <i class="fas fa-rupee-sign"></i> <%= booking.booking_price %></p>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

  <!-- Review Modal -->

        <div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="ReviewModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ReviewModalLabel">Leave a Review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= simple_form_for [Booking.first, @review] do |f| %>
                <div class="form-inputs">
                  <%= f.input :content %>
                  <%= f.input :rating, input_html: { min: '0', max: '5' } %>
                  <div class="mb-4">
                    <i class="far fa-star star_rating"></i><i class="far fa-star star_rating"></i><i class="far fa-star star_rating"></i><i class="far fa-star star_rating"></i><i class="far fa-star star_rating"></i>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.button :submit, class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
<script>
  let buttons = document.querySelectorAll(".modal-review-button");
  let form = document.querySelector("#new_review")
  buttons.forEach((button) => {
    button.addEventListener("click", (e) => {
      let url = `bookings/${e.target.dataset.booking}/reviews`;
      form.action = url;
    });
  });
  document.querySelector("#review_rating").style.display = "none";
  let stars = document.querySelectorAll(".star_rating");
  stars.forEach((element, index) => {
    element.addEventListener("click", (event) => {
      stars.forEach((item, itemIndex) => {
        item.classList.add("far");;
        if (itemIndex <= index) {
          item.classList.remove("far");;
          item.classList.add("fas");
          document.querySelector("#review_rating").value = itemIndex + 1;
        }
      });
    });
  });
</script>

app/views/pages/home.html.erb
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="banner-title">Green Room</h1>
        <h3 class="banner-text">Film Location Finder</h3>
        <div class="search-bar">
              <%= form_tag locations_path, method: :get do %>
              <%= text_field_tag :query,
              params[:query],
              class: "form-control my-form",
              placeholder: "Type to Search"
              %>
              <% end %>
      </div>
    </div>
  </div>
</header>

<section class="my-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
      </div>
    </div>
  </div>
</section>

<div class="banner-carousel">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dc3qodxke/image/upload/v1559018911/war_esovaj.jpg" class="d-block w-100" alt="#">
        <div class="carousel-caption d-none d-md-block">
          <h5>Green Room: Location Finder</h5>
          <p></p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="https://thewallpaper.co//wp-content/uploads/2016/03preview/clouds-drum-and-bass-liquicity-yoga-wide-hd-wallpaper-iphone-background-images-desktop-images-high-resolution-1920x1080.jpg" class="d-block w-100" alt="#">
        <div class="carousel-caption d-none d-md-block">
          <h5>Hollywood Locations. B-list pricing</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dc3qodxke/image/upload/v1559024560/city_dyobvl.jpg" class="d-block w-100" alt="#">
        <div class="carousel-caption d-none d-md-block">
          <h5>Green Room</h5>
          <p>Location Finder</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="p-3">
  <div class="cards">
    <%= link_to locations_path, { class: "nounderline" } do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1484447089447-a742155835e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)">
        <p>Mumbai</p>
      </div>
    <% end %>

    <%= link_to locations_path, { class: "nounderline" } do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1555952238-ae1739caa01a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)">
        <p>New Delhi</p>
      </div>
    <% end %>

    <%= link_to locations_path, { class: "nounderline" } do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1477091889224-8320eb2f1c66?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDdx9&auto=format&fit=crop&w=500&q=60)">
        <p>Bengaluru</p>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/delete.html.erb
<h1>Photos#delete</h1>
<p>Find me in app/views/photos/delete.html.erb</p>

app/views/photos/new.html.erb
<div class="new-location-container">
  <div class="container col-5">
    <div class="back-color">
        <div class="new-form">
          <h3 class="text-center pb-4">Upload photo.</h3>
          <%= simple_form_for([@location, @photo]) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">


              <%= f.input :picture  %>
              <%= f.input :picture_cache, as: :hidden %>
              <%= f.button :submit, class: "text-white btn btn-primary new-button" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
   From the Founders of Green Room
  </div>
</div>